### ISSUE TITLE
Checking for extreme observations and deleting these if needed

### ISSUE THREAD

**Issue by rikverlaan** [course-dprep/Airbnb_Analysis_Team6#23]

**Comment by bram-teunissen** [comment]
![Image](https://github.com/course-dprep/team-project-team_6/assets/144099044/a4e7599f-1703-436b-a506-29406592a9c7)

Look at this btw, we see a very extreme observation at 4. Maybe delete that?

**Comment by bram-teunissen** [comment]
These have been deleted, consider the issue closed
