### ISSUE TITLE
checking the strange_code.R and deleting it if it's not necessary

### ISSUE THREAD

**Issue by vscanturk** [course-dprep/Airbnb_Analysis_Team6#72]

**Comment by vscanturk** [comment]
@bram-teunissen In our analysis file there is a "strange.code_R" I guess you've taken these codes from clean.R file that you created another R file, we can check if it's necessary or not and delete afterwards. 


# the rest was already in the analyse file, I do not know whose code this is

# Difference in price between city center vs not
listings %>% group_by(in_city_center) %>% summarise(avg_price = mean(avg_price))

# Difference in location review score city center vs not
listings %>% group_by(in_city_center) %>% summarise(avg_score_location = mean(review_scores_location))

# Difference in overall review score city center vs not
listings %>% group_by(in_city_center) %>% summarise(avg_score = mean(review_scores_rating))

# Difference in overall review score for host is superhost vs not
listings %>% group_by(host_is_superhost) %>% summarise(avg_score = mean(review_scores_rating))

# Difference in checkin review score for host is superhost vs not
listings %>% group_by(host_is_superhost) %>% summarise(avg_score_checkin = mean(review_scores_checkin))

**Comment by bram-teunissen** [comment]
@TijldeVeer moved these I think. Whether they're necessary, I don't think so, I'll probably be creating other tables with kableExtra

**Comment by bram-teunissen** [comment]
This has been deleted
